import type { IssuePayload } from "../core/domain.js";
import { formatScoreRevisionFeedback, issueFromPayload, scoreIssue, type IssueScore } from "./scoring.js";

export type IssueQualityReport = {
  blocking: string[];
  warnings: string[];
  score: IssueScore;
  revisionFeedback: string[];
};

export function assessIssueQuality(roughInput: string, payload: IssuePayload): IssueQualityReport {
  const body = payload.body;
  const normalizedBody = normalize(body);
  const normalizedRough = normalize(roughInput);
  const score = scoreIssue(issueFromPayload(payload));
  const blocking: string[] = [];
  const warnings: string[] = [];
  const revisionFeedback: string[] = [];

  if (normalizedRough.length >= 50 && normalizedBody.includes(normalizedRough)) {
    blocking.push("Issue body appears to include the rough input verbatim.");
    revisionFeedback.push("Rewrite the rough input into maintainer-facing sections instead of copying it verbatim.");
  }

  if (/\b(ai-generated|generated by ai|generated by codex|as an ai)\b/i.test(body)) {
    blocking.push("Issue body includes visible AI-generation disclosure.");
    revisionFeedback.push("Remove visible AI-generation or Codex disclosure from the issue body.");
  }

  if (payload.kind === "bug") {
    if (!hasHeading(body, "observed") && !hasHeading(body, "actual")) {
      warnings.push("Bug issue does not clearly separate observed or actual behavior.");
    }
    if (!hasHeading(body, "expected")) {
      warnings.push("Bug issue does not clearly state expected behavior.");
    }
  }

  if (/\b[A-Z]:[\\/][^\s)`]+/.test(body)) {
    warnings.push("Issue body includes a local filesystem path; keep it only if it is actionable for maintainers.");
  }

  if (/TODO|TBD|fill me in/i.test(body)) {
    warnings.push("Issue body contains placeholder wording.");
  }

  if (score.total < 75) {
    warnings.push(`Issue quality score is ${score.total}/${score.maximum} (${score.grade}); target at least 75/100 before creating.`);
  }
  if (score.total < 55) {
    blocking.push(`Issue quality score is ${score.total}/${score.maximum}; draft is not maintainer-ready.`);
  }
  revisionFeedback.push(...formatScoreRevisionFeedback(score));

  return { blocking, warnings, score, revisionFeedback };
}

export function formatQualityWarnings(report: IssueQualityReport): string {
  const lines = [
    ...report.blocking.map((warning) => `Blocking quality gate: ${warning}`),
    ...report.warnings.map((warning) => `Quality warning: ${warning}`),
  ];
  return lines.length ? `${lines.join("\n")}\n` : "";
}

function normalize(value: string): string {
  return value.toLowerCase().replace(/\s+/g, " ").trim();
}

function hasHeading(body: string, term: string): boolean {
  return new RegExp(`^#{2,6}\\s+.*${term}`, "im").test(body);
}
