import { describe, expect, test } from "bun:test";
import { assessIssueQuality } from "./quality.js";
import type { IssuePayload } from "../core/domain.js";

const payload: IssuePayload = {
  title: "Inventory duplicates after reconnect",
  kind: "bug",
  labels: ["bug"],
  body: "## Summary\nInventory duplicates after reconnect.\n\n## Observed Behavior\nItems duplicate.\n\n## Expected Behavior\nItems remain stable.",
  confidence: 0.8,
  missingInformation: [],
  contextSummary: [],
};

describe("issue quality gates", () => {
  test("blocks rough input leakage and visible AI disclosure", () => {
    const report = assessIssueQuality("inventory duplicates after reconnect when the socket resumes", {
      ...payload,
      body: "## Summary\ninventory duplicates after reconnect when the socket resumes\n\nGenerated by AI.",
    });

    expect(report.blocking).toContain("Issue body appears to include the rough input verbatim.");
    expect(report.blocking).toContain("Issue body includes visible AI-generation disclosure.");
  });

  test("warns when bug issue shape is incomplete", () => {
    const report = assessIssueQuality("inventory bug", {
      ...payload,
      body: "## Summary\nInventory duplicates.",
    });

    expect(report.warnings).toContain("Bug issue does not clearly separate observed or actual behavior.");
    expect(report.warnings).toContain("Bug issue does not clearly state expected behavior.");
  });
});
